spring.application.name=shop
# ==============================================================
# SERVER & API CONFIGURATION
# ==============================================================
server.port=2525
server.servlet.context-path=/api/v1

# ==============================================================
# DATABASE CONFIGURATION (MySQL)
# ==============================================================
spring.datasource.url=jdbc:mysql://localhost:3306/mercado_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==============================================================
# JPA & HIBERNATE CONFIGURATION
# ==============================================================
# IMPORTANTE: En producción debe ser 'validate' o 'none', y se usan herramientas como Flyway.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ==============================================================
# SPRING SECURITY & JWT (Custom Properties)
# ==============================================================
security.jwt.secret-key=${JWT_SECRET}
security.jwt.expiration-time=86400000